server:
  port: 8082

spring:

  datasource:
    url: jdbc:mysql://localhost:3306/wl
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource # 使用druid数据源
    driver-class-name: com.mysql.jdbc.Driver
    username: root
mybatis:
  type-aliases-package: com.asiainfo.pojo
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath*:mapper/*xml

testconfig:
    url:   testurl
    name: liuguoqqq

